name = "ValueFunctions"
uuid = "31c4d4ac-5a00-4604-9840-19cb78338d47"
version = "0.1.1"
authors = ["Joscha Krug <joscha.krug@proton.me>"]

[deps]
GriddedFunctions = "15489a28-470a-4c47-be98-4174d0f03947"

[compat]
GriddedFunctions = "0.1.1"
